Node (User, Devices, Card, Bank)

Edges (Connections, Similarity(M/B))

Node features (Attributes)

Labels (Node levels, edge - level, graph level)

## Import Thư viện

In [1]:
import pandas as pd

In [2]:
bank_account_df = pd.read_csv("/content/drive/Othercomputers/My Laptop/Shopee/fraud_shopee/bank_accounts.csv")
credit_card_df = pd.read_csv("/content/drive/Othercomputers/My Laptop/Shopee/fraud_shopee/credit_cards.csv")
devices_df = pd.read_csv("/content/drive/Othercomputers/My Laptop/Shopee/fraud_shopee/devices.csv")
orders_df = pd.read_csv("/content/drive/Othercomputers/My Laptop/Shopee/fraud_shopee/orders.csv")


<ipython-input-2-219d00811aa2>:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  bank_account_df = pd.read_csv("/content/drive/Othercomputers/My Laptop/Shopee/fraud_shopee/bank_accounts.csv")


In [3]:
bank_account_df.head()

userid     bank_account
0  21829134  923302000003892
1  95910542   11002023212822
2  96941876        189303223
3  23452396    2280003199803
4  12647942   32002028484803

In [4]:
credit_card_df.head()

userid               credit_card
0  2579938  832299xxxxxx4902|02-2019
1  2154902  322429xxxxxx3848|05-2020
2  5578604  322429xxxxxx1293|11-2016
3  2051728  388329xxxxxx4303|09-2016
4  6216212  322421xxxxxx4238|05-2018

In [5]:
devices_df.head()

userid                                        device
0   10499978  0Zu/mWZ4cFsvobYglgZEc5VSxwwajRwrm74pBuwnrTu=
1   54526742  zBMRKyz98iy5Z7sh+JIOdF612J1CB8ggvFBI6MP361q=
2   33152428  KXC0oY3MMrTG+bnlFFvBPXZC5PW8iw6kgWztENWdIJg=
3   55020986  anRXS7+zVgCGKz5C9X3dzewIhSdojGEi5TO07pb2y+K=
4  100471502  hbIARr+USwvjjzc8QUVtD5a/apR1DJX6P3fYvgDL4gW=

In [6]:
orders_df.head()

orderid  buyer_userid  seller_userid
0  1953278092      47388162       20822974
1  1953295120      26855196       16416890
2  1953306402     121296714       28477978
3  1953314712     131221930       72837912
4  1953381964     183398314       28423332

## Lấy ra toàn bộ userid, device, bank_account,credit_card trong 3 bảng device, bank_account, credit_card để tạo các node

### Userid

In [7]:
userid = pd.concat((bank_account_df['userid'], devices_df['userid'], credit_card_df['userid']), ignore_index=True)
userid

0           21829134
1           95910542
2           96941876
3           23452396
4           12647942
             ...    
1819855     25879226
1819856      9331492
1819857      2890486
1819858    107429252
1819859     78930744
Name: userid, Length: 1819860, dtype: int64

In [8]:
userid = pd.DataFrame(userid.drop_duplicates().reset_index(drop=True))
userid

userid
0        21829134
1        95910542
2        96941876
3        23452396
4        12647942
...           ...
483661  232855458
483662  232874980
483663   89713360
483664  105475942
483665   80147728

[483666 rows x 1 columns]

In [9]:
# Sort to define the order of nodes
sort_userid = userid.sort_values(by='userid').set_index('userid')

# Map IDs to start from 0
sort_userid = sort_userid.reset_index(drop=False)
user_id_mapping = sort_userid["userid"]

In [10]:
user_id_mapping

0             21386
1             21396
2             21446
3             21456
4             21470
            ...    
483661    235667058
483662    235667078
483663    235667830
483664    235667936
483665    235667982
Name: userid, Length: 483666, dtype: int64

### Device

Lấy ra device từ bảng devices

In [11]:
devices = devices_df['device']
devices = pd.DataFrame(devices.drop_duplicates().reset_index(drop=True))
devices

device
0        0Zu/mWZ4cFsvobYglgZEc5VSxwwajRwrm74pBuwnrTu=
1        zBMRKyz98iy5Z7sh+JIOdF612J1CB8ggvFBI6MP361q=
2        KXC0oY3MMrTG+bnlFFvBPXZC5PW8iw6kgWztENWdIJg=
3        anRXS7+zVgCGKz5C9X3dzewIhSdojGEi5TO07pb2y+K=
4        hbIARr+USwvjjzc8QUVtD5a/apR1DJX6P3fYvgDL4gW=
...                                               ...
1363282  ZSTXD6wfHN/1qPVqMrIbwHYX5ELWlUPO3NFXCHK50Mc=
1363283  o+9gbX201ITS3MuMZYjuZUzV7sOoR57/0ttyX3eSWTA=
1363284  NZhNiXYhArpPquzrqh/kVj2IZ3QPRKm6FH90vsTlhiy=
1363285  dZ7YqVTprtTvLT4qS0YEWsn9EJahBJVQtTLKC6WaHZA=
1363286  Mtmaool7T0CUyHJD112gAw6OiTl4tVSAPK4njG9B56y=

[1363287 rows x 1 columns]

In [12]:
devices_id_mapping = devices['device']
devices_id_mapping

0          0Zu/mWZ4cFsvobYglgZEc5VSxwwajRwrm74pBuwnrTu=
1          zBMRKyz98iy5Z7sh+JIOdF612J1CB8ggvFBI6MP361q=
2          KXC0oY3MMrTG+bnlFFvBPXZC5PW8iw6kgWztENWdIJg=
3          anRXS7+zVgCGKz5C9X3dzewIhSdojGEi5TO07pb2y+K=
4          hbIARr+USwvjjzc8QUVtD5a/apR1DJX6P3fYvgDL4gW=
                               ...                     
1363282    ZSTXD6wfHN/1qPVqMrIbwHYX5ELWlUPO3NFXCHK50Mc=
1363283    o+9gbX201ITS3MuMZYjuZUzV7sOoR57/0ttyX3eSWTA=
1363284    NZhNiXYhArpPquzrqh/kVj2IZ3QPRKm6FH90vsTlhiy=
1363285    dZ7YqVTprtTvLT4qS0YEWsn9EJahBJVQtTLKC6WaHZA=
1363286    Mtmaool7T0CUyHJD112gAw6OiTl4tVSAPK4njG9B56y=
Name: device, Length: 1363287, dtype: object

### Bank_accounts

In [13]:
bank_account = bank_account_df['bank_account']
bank_account = pd.DataFrame(bank_account.drop_duplicates().reset_index(drop=True))
bank_account

bank_account
0       923302000003892
1        11002023212822
2             189303223
3         2280003199803
4        32002028484803
...                 ...
335911  084902023320802
335912  023102020991822
335913       0090343142
335914       3330993800
335915       0942232333

[335916 rows x 1 columns]

In [14]:
bank_account_id_mapping = bank_account['bank_account']
bank_account_id_mapping

0         923302000003892
1          11002023212822
2               189303223
3           2280003199803
4          32002028484803
               ...       
335911    084902023320802
335912    023102020991822
335913         0090343142
335914         3330993800
335915         0942232333
Name: bank_account, Length: 335916, dtype: object

### Credit_card

In [15]:
credit_card = credit_card_df['credit_card']
credit_card = pd.DataFrame(credit_card.drop_duplicates().reset_index(drop=True))
credit_card

credit_card
0      832299xxxxxx4902|02-2019
1      322429xxxxxx3848|05-2020
2      322429xxxxxx1293|11-2016
3      388329xxxxxx4303|09-2016
4      322421xxxxxx4238|05-2018
...                         ...
37362  839199xxxxxx3838|12-2022
37363  398138xxxxxx2208|08-2019
37364  839330xxxxxx9180|08-2022
37365  899933xxxxxx2930|06-2021
37366  392843xxxxxx2933|07-2021

[37367 rows x 1 columns]

In [16]:
credit_card_id_mapping = credit_card['credit_card']
credit_card_id_mapping

0        832299xxxxxx4902|02-2019
1        322429xxxxxx3848|05-2020
2        322429xxxxxx1293|11-2016
3        388329xxxxxx4303|09-2016
4        322421xxxxxx4238|05-2018
                   ...           
37362    839199xxxxxx3838|12-2022
37363    398138xxxxxx2208|08-2019
37364    839330xxxxxx9180|08-2022
37365    899933xxxxxx2930|06-2021
37366    392843xxxxxx2933|07-2021
Name: credit_card, Length: 37367, dtype: object

## Xây dựng Mapping bằng chỉ số index của các bảng *_df

### Mapping of device

In [17]:
devices_userid_mapping = devices_df.copy(deep=True)
devices_userid_mapping

userid                                        device
0         10499978  0Zu/mWZ4cFsvobYglgZEc5VSxwwajRwrm74pBuwnrTu=
1         54526742  zBMRKyz98iy5Z7sh+JIOdF612J1CB8ggvFBI6MP361q=
2         33152428  KXC0oY3MMrTG+bnlFFvBPXZC5PW8iw6kgWztENWdIJg=
3         55020986  anRXS7+zVgCGKz5C9X3dzewIhSdojGEi5TO07pb2y+K=
4        100471502  hbIARr+USwvjjzc8QUVtD5a/apR1DJX6P3fYvgDL4gW=
...            ...                                           ...
1430306    7061456  ZSTXD6wfHN/1qPVqMrIbwHYX5ELWlUPO3NFXCHK50Mc=
1430307   26416970  o+9gbX201ITS3MuMZYjuZUzV7sOoR57/0ttyX3eSWTA=
1430308   79633116  NZhNiXYhArpPquzrqh/kVj2IZ3QPRKm6FH90vsTlhiy=
1430309   19883370  dZ7YqVTprtTvLT4qS0YEWsn9EJahBJVQtTLKC6WaHZA=
1430310     698234  Mtmaool7T0CUyHJD112gAw6OiTl4tVSAPK4njG9B56y=

[1430311 rows x 2 columns]

In [18]:
device_map = devices_id_mapping.reset_index().set_index('device').to_dict()
devices_userid_mapping['device'] = devices_userid_mapping['device'].map(device_map['index']).astype(int)
# devices_userid_mapping

In [19]:
userid_map = user_id_mapping.reset_index().set_index('userid').to_dict()
devices_userid_mapping['userid'] = devices_userid_mapping['userid'].map(userid_map['index']).astype(int)
devices_userid_mapping

userid   device
0         25579        0
1        158962        1
2         99113        2
3        160289        3
4        254339        4
...         ...      ...
1430306   14035  1363282
1430307   79792  1363283
1430308  216355  1363284
1430309   57900  1363285
1430310     849  1363286

[1430311 rows x 2 columns]

In [20]:
edge_index_device = devices_userid_mapping[['userid', 'device']].values.transpose()
edge_index_device

array([[  25579,  158962,   99113, ...,  216355,   57900,     849],
       [      0,       1,       2, ..., 1363284, 1363285, 1363286]])

### Mapping of Bank_account

In [21]:
bank_account_mapping = bank_account_df.copy(deep=True)
bank_account_mapping

userid     bank_account
0       21829134  923302000003892
1       95910542   11002023212822
2       96941876        189303223
3       23452396    2280003199803
4       12647942   32002028484803
...          ...              ...
350836  23568930  084902023320802
350837  17207934  023102020991822
350838  23862272       0090343142
350839  23983072       3330993800
350840  13282776       0942232333

[350841 rows x 2 columns]

In [22]:
bank_accounts_map = bank_account_id_mapping.reset_index().set_index('bank_account').to_dict()
bank_account_mapping['bank_account'] = bank_account_mapping['bank_account'].map(bank_accounts_map['index']).astype(int)
# bank_account_mapping

In [23]:
userid_map = user_id_mapping.reset_index().set_index('userid').to_dict()
bank_account_mapping['userid'] = bank_account_mapping['userid'].map(userid_map['index']).astype(int)
bank_account_mapping

userid  bank_account
0        64915             0
1       246174             1
2       247920             2
3        70291             3
4        33422             4
...        ...           ...
350836   70678        335911
350837   48616        335912
350838   71594        335913
350839   71939        335914
350840   35873        335915

[350841 rows x 2 columns]

In [24]:
edge_index_bank = bank_account_mapping[['userid', 'bank_account']].values.transpose()
edge_index_bank

array([[ 64915, 246174, 247920, ...,  71594,  71939,  35873],
       [     0,      1,      2, ..., 335913, 335914, 335915]])

### Mapping of Credit_card

In [25]:
credit_card_mapping = credit_card_df.copy(deep=True)
credit_card_mapping

userid               credit_card
0        2579938  832299xxxxxx4902|02-2019
1        2154902  322429xxxxxx3848|05-2020
2        5578604  322429xxxxxx1293|11-2016
3        2051728  388329xxxxxx4303|09-2016
4        6216212  322421xxxxxx4238|05-2018
...          ...                       ...
38703   25879226  839199xxxxxx3838|12-2022
38704    9331492  398138xxxxxx2208|08-2019
38705    2890486  839330xxxxxx9180|08-2022
38706  107429252  899933xxxxxx2930|06-2021
38707   78930744  392843xxxxxx2933|07-2021

[38708 rows x 2 columns]

In [26]:
credit_card_map = credit_card_id_mapping.reset_index().set_index('credit_card').to_dict()
credit_card_mapping['credit_card'] = credit_card_mapping['credit_card'].map(credit_card_map['index']).astype(int)
# credit_card_mapping

In [27]:
userid_map = user_id_mapping.reset_index().set_index('userid').to_dict()
credit_card_mapping['userid'] = credit_card_mapping['userid'].map(userid_map['index']).astype(int)
credit_card_mapping

userid  credit_card
0        4968            0
1        3995            1
2       10183            2
3        3758            3
4       11536            4
...       ...          ...
38703   77970        37362
38704   21560        37363
38705    5526        37364
38706  267802        37365
38707  214848        37366

[38708 rows x 2 columns]

In [28]:
edge_index_credit = credit_card_mapping[['userid', 'credit_card']].values.transpose()
edge_index_credit

array([[  4968,   3995,  10183, ...,   5526, 267802, 214848],
       [     0,      1,      2, ...,  37364,  37365,  37366]])

## Build dataset

In [29]:
!pip install torch_geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.6/661.6 kB 10.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for torch_geometric: filename=torch_geometric-2.3.1-py3-none-any.whl size=910459 sha256=66f7af990adf42116a10c445d0a62492d7e56fe913276d86a2c225d44093c4dd
  Stored in directory: /root/.cache/pip/wheels/ac/dc/30/e2874821ff308ee67dcd7a66dbde912411e19e35a1addda028
Successfully built torch_geometric


In [30]:
from torch_geometric.data import HeteroData
data = HeteroData()

data['user'].x = userid
data['device'].x = devices
data['bank_account'].x = bank_account
data['credit_card'].x = credit_card

data['user', 'rating', 'device'].edge_index = edge_index_device
data['user', 'rating', 'bank_account'].edge_index = edge_index_bank
data['user', 'rating', 'credit_card'].edge_index = edge_index_credit

In [31]:
data['user']

{'x':            userid
0        21829134
1        95910542
2        96941876
3        23452396
4        12647942
...           ...
483661  232855458
483662  232874980
483663   89713360
483664  105475942
483665   80147728

[483666 rows x 1 columns]}

## Test code

In [32]:
# from torch_geometric.data import HeteroData
# import torch

# data = HeteroData()

# # Thêm dữ liệu nút
# data['paper'].x = torch.randn(4, 128)
# data['author'].x = torch.randn(2, 128)

# # Thêm dữ liệu cạnh
# data['paper', 'cites', 'paper'].edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
# data['author', 'writes', 'paper'].edge_index = torch.tensor([[0, 1], [0, 2]])

# # Truy cập dữ liệu nút và cạnh
# paper_node_data = data['paper']
# cites_edge_data = data['paper', 'cites', 'paper']

In [33]:
# paper_node_data

In [34]:
# cites_edge_data